export const CREATED_SUCCES_CODE = 201;
export const REQUEST_ERROR_CODE = 400;
export const AUTHORIZATION_ERROR_CODE = 401;
export const FORBIDDEN_ERROR_CODE = 403;
export const NOT_FOUND_ERROR_CODE = 404;
export const DUBLICATE_ERROR_CODE = 409;
export const INTERNAL_SERVER_ERROR_CODE = 500;
